# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            'György Kovács'
tagline:          'György Kovács'
description:	   'PhD in Informatics'
url:              https://gykovacs.github.io
baseurl:          /

author:
  name:           'György Kovács'
  url:            https://gykovacs.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/gykovacs

scholar:
    style: _layouts/apa-note-num
    bibliography: refs.bib
    bibliography_template: bibtemplate
    replace_strings: true
    query: "@*"
    
